//자바스크립트의try catch 동기적으로 작동한다.
try{
  setTimeout(() => {
    미ㅐ;
  }, 2000)
  // setInterval(() => {})
}catch(e){  
  console.log("잘못된 값을 입력")
}finally{
  e.name
}

//비동기 함수 처리 
 //setTimeout //동기는 동기 흐름 -> 몇초뒤에 실행시킬 수 없으니까 // 몇초뒤에
 //setInterval // 몇초마다


 setTimeout(() => {
  try{
    ㅇ려;
  }catch(error){
    console.log("잘못된 값입니다")
  }
 }, 2000)





